apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: joomladb
  name: joomladb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: joomladb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: joomladb
    spec:
      nodeSelector:
        group: wprofile
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
          image: mysql:5.7
          name: joomladb
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
